[package]
name = "sled_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gluesql_core = { version = "0.9", path = "../../core" }
gluesql_common = { path = "../../common", features = ["sled-storage"] }

async-trait = "0.1"
iter-enum = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

bincode = { version = "1", optional = true }
sled = { version = "0.34", optional = true }

[features]
default = ["alter-table", "sorter", "index", "transaction"]

alter-table = ["gluesql_core/alter-table", "gluesql_common/alter-table"]
sorter = ["gluesql_core/sorter"]
index = ["gluesql_core/index", "gluesql_common/index"]
transaction = ["gluesql_core/transaction"]
