[package]
name = "sled-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
gluesql-core = { version = "0.9", path = "../../core" }
gluesql-utils = { path = "../../utils", features = ["sled-storage"] }

async-trait = "0.1"
iter-enum = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

bincode = "1"
sled = "0.34"

[features]
default = ["index", "transaction"]

alter-table = ["gluesql-core/alter-table", "gluesql-utils/alter-table"]
sorter = ["gluesql-core/sorter"]
index = ["gluesql-core/index", "gluesql-utils/index"]
transaction = ["gluesql-core/transaction"]
