[package]
name = "memory-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
gluesql-core = { version = "0.9", path = "../../core" }

async-trait = "0.1"

[features]
default = ["alter-table", "index", "transaction"]

alter-table = ["gluesql-core/alter-table"]
index = ["gluesql-core/index"]
transaction = ["gluesql-core/transaction"]
