[package]
name = "gluesql_common"
version = "0.1.0"
edition = "2021"


[dependencies]
futures = "0.3"
pin-project = "1"
indexmap = "1"

[features]
alter-table = []
sorter = []
index = []
transaction = []

sled-storage = []
