[package]
name = "sled-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
gluesql-core = { version = "0.9", path = "../../core", features = ["index", "transaction"] }
gluesql-utils = { path = "../../utils" }

async-trait = "0.1"
iter-enum = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
bincode = "1"
sled = "0.34"

[dev-dependencies]
gluesql-test-suite = { path = "../../test-suite" }

criterion = "0.3"
tokio = "1"

[features]
default = ["alter-table"]

alter-table = ["gluesql-core/alter-table", "gluesql-test-suite/alter-table"]
